# Generated by Django 4.1.6 on 2023-02-11 16:38

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('minTemp', models.BigIntegerField()),
                ('maxTemp', models.BigIntegerField()),
                ('minHumi', models.BigIntegerField()),
                ('maxHumi', models.BigIntegerField()),
                ('avatar', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='img/')),
                ('fintime', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
