# Generated by Django 4.1.5 on 2023-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=10)),
                ('minTemp', models.CharField(max_length=10)),
                ('maxTemp', models.CharField(max_length=10)),
                ('minHumi', models.CharField(max_length=10)),
                ('maxHumi', models.CharField(max_length=10)),
            ],
        ),
    ]
