# Generated by Django 4.1.5 on 2023-02-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tata',
            name='plant',
            field=models.CharField(max_length=100),
        ),
    ]
