# Generated by Django 4.1.5 on 2023-02-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0002_tata_name_alter_tata_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tata',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/'),
        ),
        migrations.AddField(
            model_name='tata',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbnails'),
        ),
    ]
