# Generated by Django 4.1.5 on 2023-02-10 04:15

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0003_tata_avatar_tata_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tata',
            name='thumbnails',
        ),
        migrations.AlterField(
            model_name='tata',
            name='avatar',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='media/img/'),
        ),
    ]
