# Generated by Django 4.1.5 on 2023-02-10 04:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0004_remove_tata_thumbnails_alter_tata_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tata',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='media/img/'),
        ),
    ]
