# Generated by Django 4.1.5 on 2023-02-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0005_alter_tata_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tata',
            name='maxHumi',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tata',
            name='maxTemp',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tata',
            name='minHumi',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tata',
            name='minTemp',
            field=models.BigIntegerField(),
        ),
    ]
